### PR TITLE
Documentation correction.

### PR DESCRIPTION
**Pull request by Alphapixels**
As I see from the source code you need to pass a valid instance of Token to the Auth class, so, I guess this will prevent some confusion.

### CODE REVIEW

**Comment by philipbrown** [comment]
You pass the `Token` to the `attempt()` method of the `Auth` class, not on instantiation.

**Comment by Alphapixels** [comment]
It seems to completely go bonkers if you don't pass it on instantiation. It gives an error of wrong argument.

**Comment by philipbrown** [comment]
Hmm, sounds like you haven't got the latest version of the code. Are you using composer to pull it into an existing project?

**Comment by Alphapixels** [comment]
Indeed using composer.

**Comment by philipbrown** [comment]
Try that c3306cd0e8e0c83c6b90cb8ef80e2883a6db2c73

**Pull request closed without merging**
